spring:
  config:
    import: "optional:classpath:application-db.yml"

  application:
    name: portfolio

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
  security:
    user:
      name: test
      password: 1234

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:/Users/jihyun/Documents/project/portfolioSave/save/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB


server:
  port: 8080